[tool.poetry]
name = "publ.plaidweb.site"
version = "0.1.0"
description = ""
authors = ["fluffy <fluffy@beesbuzz.biz>"]

[tool.poetry.dependencies]
python = "^3.8.1"
gunicorn = "^20.1.0"
python-memcached = "^1.59"
pushl = "^0.3.3"
publ = {version = "^0.7.18", extras = ["search","auth"]}
flask-github-webhook = "^0.2.0"

[tool.poetry.dev-dependencies]
isort = "^5.10.1"
autopep8 = "^2.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
