[tool.poetry]
name = "publ.plaidweb.site"
version = "0.1.0"
description = ""
authors = ["fluffy <fluffy@beesbuzz.biz>"]

[tool.poetry.dependencies]
python = "^3.8"
flask-hookserver = "^1.1.0"
gunicorn = "^20.0.4"
publ = "^0.7.1"
python-memcached = "^1.59"
Pushl = "^0.3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
